apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: jenkins-operator
  namespace: PROJECT
spec:
  channel: "4.7"
  installPlanApproval: Automatic
  name: jenkins-operator
  source: jenkins-operator
  sourceNamespace: openshift-marketplace
  startingCSV: jenkins-operator.0.0.0
