name: E2E Tests
on: [push, workflow_dispatch, pull_request]￼
jobs:
  test-and-build:
    name: Test+Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1'

      - name: Install Kubectl
        uses: azure/setup-kubectl@v1

      - name: Install Kind
        uses: helm/kind-action@v1.1.0
        with:
          cluster_name: jenkins-automation-operator-test

      - name: Test verify
        run: make verify
      - name: Suite Test
        run: make test 
      - name: Suite Test with Cluster
        run: make test USE_EXISTING_CLUSTER=true
      - name: 
        run: bash <(curl -s https://codecov.io/bash) 
